-- CreateTable
CREATE TABLE "Dm" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "message" TEXT NOT NULL,
    "senderId" INTEGER NOT NULL,
    "recieverId" INTEGER NOT NULL,
    "time" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Dm_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "Pupil" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Dm_recieverId_fkey" FOREIGN KEY ("recieverId") REFERENCES "Pupil" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
